ci/migration gha multpile changes
newrelic/nri-discovery-kubernetes pull request #18
Opened 2020-10-21 15:22 UTC by jportasa

ci/migration gha multpile changes

2020-10-21 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-discovery-kubernetes?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-discovery-kubernetes?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-discovery-kubernetes?pullRequest=18) it.</sub>

2021-02-09 14:44 UTC, paologallinaharbur commented on build/package/windows/nri-386-installer/Product.wxs
> +        <ComponentGroup Id="CustomPluginsComponent" Directory="CustomPluginsFolder">
If we are not publishing msi, should't we remove all windows configs?

2021-02-09 15:11 UTC, roobre commented on build/package/windows/nri-386-installer/Product.wxs
> +        <ComponentGroup Id="CustomPluginsComponent" Directory="CustomPluginsFolder">
In fact I think I wanted to do it but then something crashed and I forgot. The current files are mostly a copypaste from redis and are not very useful anyway.

2021-02-15 11:17 UTC, arvdias requested changes

2021-02-15 11:17 UTC, arvdias commented on build/.goreleaser.yml
> +      - 386
do we want to release for 32.bit windows? I mean I don't think K8s runs on Windows 32 bit nodes, https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support
I would remove  support for that.

2021-02-15 11:17 UTC, arvdias commented on build/.goreleaser.yml
> +  - id: nri-discovery-kubernetes-deb
you could merge deb and rpm in the same "build" and use "overrides" to change the filename template

2021-02-15 12:20 UTC, paologallinaharbur commented on build/.goreleaser.yml
> +      - 386
👍

2021-02-15 12:21 UTC, paologallinaharbur commented on .github/workflows/push_pr.yml
> +  test-windows:
same here

2021-02-15 12:22 UTC, paologallinaharbur commented on build/windows/fix_archives.sh
> +#
Should we remove this as well?

2021-02-15 12:22 UTC, paologallinaharbur commented on build/windows/fix_archives.sh
> +#
let's say the whole build/windows if we are not supporting it

2021-02-15 12:23 UTC, paologallinaharbur commented on build/windows/fix_archives.sh
> +#
or we are actually supporting windows but not creating the msi?

2021-02-15 14:59 UTC, paologallinaharbur commented on build/.goreleaser.yml
> +  #- go mod download
it is commented out, but we are using go mod

2021-02-15 14:59 UTC, paologallinaharbur approved these changes

2021-02-15 15:09 UTC, roobre commented on build/.goreleaser.yml
> +  - id: nri-discovery-kubernetes-deb
Do you have a link for a pipeline where we made that change? That way I reduce the chance of human error :)

2021-02-15 15:10 UTC, roobre commented on build/windows/fix_archives.sh
> +#
Yes, we release .exe (.zip with .exe inside), but not MSI. Rationale for this was that this will likely be useful only inside a docker image.

2021-02-15 15:14 UTC, roobre commented on build/.goreleaser.yml
> +  #- go mod download
This is done at some point by make, in the `deps` recipe. I can uncomment it above as well just in case, should be a noop.

2021-02-15 15:15 UTC, roobre commented on build/windows/fix_archives.sh
> +#
I removed it since we don't produce `_dirty` archives for this integration.

2021-02-15 15:17 UTC, roobre commented on build/.goreleaser.yml
> +      - 386
Stripped!

2021-02-15 15:18 UTC, roobre commented on build/.goreleaser.yml
> +  #- go mod download
Uncommented, just to make goreleaser functional on its own.

2021-02-15 15:41 UTC, roobre commented on build/.goreleaser.yml
> +  - id: nri-discovery-kubernetes-deb
Backported from `nri-cassandra`, please check whether it seems ok now

2021-02-15 15:59 UTC, davidbrota reviewed
I've left some comments

2021-02-15 15:59 UTC, davidbrota commented on .github/ISSUE_TEMPLATE/config.yml
> +    url:  https://github.com/newrelic/nri-redis/blob/master/README.md#support
s/nri-redis/nri-discovery-kubernetes

2021-02-15 15:59 UTC, davidbrota commented on build/.goreleaser.yml
> +      - -s -w -X main.integrationVersion={{.Version}} -X main.gitCommit={{.Commit}}
nri-discovery-kubernetes doesn't have those variables in its main. Neither supports the version cli flag. We could open an issue to address this in the future.

2021-02-15 15:59 UTC, davidbrota commented on build/nix/fix_archives.sh
> +  mv ${TARBALL_CONTENT_PATH}/${INTEGRATION}-definition.yml ${TARBALL_CONTENT_PATH}/var/db/newrelic-infra/newrelic-integrations/
this integration neither has definition nor configuration file. Will this script fail?

2021-02-15 16:23 UTC, paologallinaharbur commented on build/.goreleaser.yml
> +      - -s -w -X main.integrationVersion={{.Version}} -X main.gitCommit={{.Commit}}
in other integrations we were using the very same gha PR to add that flag

2021-02-15 16:46 UTC, roobre commented on build/nix/fix_archives.sh
> +  mv ${TARBALL_CONTENT_PATH}/${INTEGRATION}-definition.yml ${TARBALL_CONTENT_PATH}/var/db/newrelic-infra/newrelic-integrations/
This script is in fact unused, as tarballs have a different format for this integration (just the binary sitting there). I'll garbage collect the file.

2021-02-15 16:54 UTC, roobre commented on build/.goreleaser.yml
> +      - -s -w -X main.integrationVersion={{.Version}} -X main.gitCommit={{.Commit}}
I took a quick look at this and it seems that it wraps viper around flag, so I saw no quick way to add this. I have, however, corrected the package path.

2021-02-17 15:30 UTC, davidbrota commented on .github/workflows/push_pr.yml
> +  test-windows:
I think we could delete this, could we?

2021-02-17 15:33 UTC, davidbrota approved these changes
LGTM

2021-02-22 10:47 UTC, arvdias approved these changes

2021-02-22 10:48 UTC, merged