Integration tests
newrelic/nri-discovery-kubernetes pull request #33
Opened 2021-05-25 18:00 UTC by paologallinaharbur

2021-05-26 09:09 UTC, paologallinaharbur commented
This Pr Has been created on the top of https://github.com/newrelic/nri-discovery-kubernetes/pull/30 in order to check in advance dependency changes

2021-05-26 10:51 UTC, paologallinaharbur commented
The tests are flaky in 1.21 and I had to remove the ports, otherwise it was failing from time to time.
After removing the ports the error not longer showed up

Possibly connected to https://github.com/kubernetes/kubernetes/issues/100889

2021-05-31 07:29 UTC, invidian requested changes

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	t.Run("with_no_namespace", func(t *testing.T) {
Name of this test case is `Test_discovery_when_succeeds/with_no_namespace`. I'm missing a verb here :smile:

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	defer k8sClient.CoreV1().Pods("default").Delete(pod.Name, &metav1.DeleteOptions{})
I suggest using `t.Cleanup` instead.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	// Parse kubeconfig
```suggestion
	// Parse kubeconfig.
```

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	// create the k8s client to populate cluster
```suggestion
	// Create the k8s client to populate cluster.
```

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +		t.Fatal(err)
I'd annotate the errors (use `Fatalf`, similar to `fmt.Errorf`) for nicer error messages on failing tests.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	time.Sleep(15 * time.Second)
Rather than using a magic number, we should loop and check pod status.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	defer k8sClient.CoreV1().Pods("default").Delete(pod.Name, &metav1.DeleteOptions{})
Also handle errors from removing and log them.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	pod, err := k8sClient.CoreV1().Pods("default").Create(getPodIntegration())
Can we use test namespace to be able to possibly run more tests in parallel?

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	if minikubeHome = os.Getenv("MINIKUBE_HOME"); minikubeHome == "" {
Can we use Insecure TLS in tests to avoid requiring minikube for tests?

2021-05-31 07:29 UTC, invidian commented on internal/http/client.go
> +		return nil, fmt.Errorf("httpClient buffer: '%s', Status %s", string(buff), resp.Status)
Maybe (also applies to other line):
```suggestion
		return nil, fmt.Errorf("httpClient buffer: %q, Status %s", string(buff), resp.Status)
```

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	// populate cluster
I'm not sure if comments like this are very helpful. Same for above and below. I think it's obvious due to variables use why certain objects are created.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +	e2eClient := getMinikubeHTTPClient(t, *config)
It's a bit confusing, that it's integration tests, but client is named e2e.

2021-05-31 07:29 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +		testPodIntegration(t, resultToTest, pod)
Rather than having assert helper, it would be better to just loop over different namespace names and have single execution code, table driven tests.

2021-05-31 08:34 UTC, paologallinaharbur commented on internal/discovery/discoverer_integration_test.go
> +		t.Fatal(err)
definetely!

2021-05-31 14:53 UTC, paologallinaharbur commented on internal/discovery/discoverer_integration_test.go
> +		testPodIntegration(t, resultToTest, pod)
Since we are not adding many more tests I am not sure if going in that direction would not result in making the tests more complex instead of easier to be managed and modified. 😕

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +	require.NoErrorf(t, err, "not expecting error when building config from kubeconfig")
https://danmux.com/posts/the_cult_of_go_test/ something worth to be aware of while using assert libraries.

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +	)
```suggestion
	})
```

I think this is more idiomatic formatting.

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +		discoverer := discovery.NewDiscoverer(nil, kubelet)
If this after all tests the discoverer, perhaps we can move the tests there?

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +		require.NotEqualf(t, resultToTest, discovery.DiscoveredItem{}, "we expect resultToTest to be populated")
I guess we rather expect that discoverer discovers test pod?

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +		require.NoErrorf(t, err, "not expecting error when running discovery with no namespaces")
Should we create 2 namespaces with 2 pods and check that at least 2 pods were found, as far as I understand, when no namespaces are configured, discovery happens for all namespaces right? I think this could be one test, then asserting the exact discovery result could be done in a separate test.

2021-05-31 15:21 UTC, invidian commented on cmd/discovery/discovery_integration_test.go
> +	t.Run("succeeds_with_no_namespace", func(t *testing.T) {
What's the point of testing that it `succeeds` when we never test when it should fail?

Maybe test like `Test_Discoverer_finds_pods_in_all_namespaces_when_no_namespaces_are_configured` would make more sense?

2021-05-31 15:31 UTC, invidian commented on internal/discovery/discoverer_integration_test.go
> +		testPodIntegration(t, resultToTest, pod)
Right. I see now, I thought `testPodIntegration` is called in all tests. I still think we could put a bit more thought into those tests to structure them better, as described in next review comments.

2021-05-31 15:50 UTC, paologallinaharbur commented on .github/workflows/push_pr.yml
> +          MINIKUBE_HOME: '/home/runner/work/_temp'
no!

2021-06-01 01:11 UTC, paologallinaharbur commented on cmd/discovery/discovery_integration_test.go
> +	retry "github.com/avast/retry-go"
also `require.Eventually`

2021-06-07 14:23 UTC, closed without merging